"""Initial migration.

Revision ID: 09cbbb8b1f0f
Revises: 
Create Date: 2024-03-31 05:18:21.153588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09cbbb8b1f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('schedule',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.alter_column('schedule',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
